import { LightningElement, api } from 'lwc';
import { loadScript } from 'lightning/platformResourceLoader';

import jsPDFResource from '@salesforce/resourceUrl/jsPDF';
import { CloseActionScreenEvent } from 'lightning/actions';

import savePdf from '@salesforce/apex/LeaseAgreementController.savePdf';
import getLeaseAgreement from '@salesforce/apex/LeaseAgreementController.getLeaseAgreement';

import { ShowToastEvent } from 'lightning/platformShowToastEvent';

export default class LeaseAgreementDownloadPdf extends LightningElement {


@api recordId;

isLoading = false;
pdfLoaded = false;
jsPDF;

renderedCallback() {

    if (this.pdfLoaded) {
        return;
    }

    this.pdfLoaded = true;

    loadScript(this, jsPDFResource)
        .then(() => {
            this.jsPDF = window.jspdf.jsPDF;

            this.generatePdf();
        })
        .catch(error => {

            this.showToast(
                'Error',
                'Unable to load jsPDF.',
                'error'
            );

            console.error(error);
        });
}

async generatePdf() {

    this.isLoading = true;

    try {

        const agreement = await getLeaseAgreement({
            leaseAgreementId: this.recordId
        });

        const pdf = new this.jsPDF({
            orientation: 'portrait',
            unit: 'mm',
            format: 'a4'
        });

        const pageWidth = pdf.internal.pageSize.getWidth();
        const pageHeight = pdf.internal.pageSize.getHeight();

        pdf.setDrawColor(0);
        pdf.setLineWidth(0.6);

        pdf.rect(
            10,
            10,
            pageWidth - 20,
            pageHeight - 20
        );

        pdf.setFont('helvetica', 'bold');
        pdf.setFontSize(22);

        pdf.text(
            'LEASE AGREEMENT',
            pageWidth / 2,
            22,
            {
                align: 'center'
            }
        );

        pdf.setFontSize(10);
        pdf.setFont('helvetica', 'normal');

        pdf.text(
            'Generated: ' +
            new Date().toLocaleDateString(),
            pageWidth - 20,
            30,
            {
                align: 'right'
            }
        );

        pdf.line(
            20,
            35,
            pageWidth - 20,
            35
        );

        let y = 45;

        pdf.setFillColor(230, 230, 230);

        pdf.rect(
            20,
            y,
            170,
            8,
            'F'
        );

        pdf.setFont('helvetica', 'bold');

        pdf.text(
            'Agreement Details',
            23,
            y + 5
        );

        y += 15;

        const rows = [
            ['Agreement', agreement.name],
            ['Property', agreement.propertyName],
            ['Tenant', agreement.tenantName],
            ['Phone', agreement.tenantPhone],
            ['Email', agreement.tenantEmail],
            ['Monthly Rent', '$' + agreement.monthlyRent],
            ['Start Date', agreement.startDate],
            ['End Date', agreement.endDate]
        ];

        rows.forEach(row => {

            pdf.setFont('helvetica', 'bold');
            pdf.text(row[0], 25, y);

            pdf.setFont('helvetica', 'normal');
            pdf.text(row[1] || '', 75, y);

            y += 9;
        });

        y += 5;

        pdf.setFillColor(230, 230, 230);

        pdf.rect(
            20,
            y,
            170,
            8,
            'F'
        );

        pdf.setFont('helvetica', 'bold');

        pdf.text(
            'Terms & Conditions',
            23,
            y + 5
        );

        y += 12;

        pdf.setFont('helvetica', 'normal');

        const wrappedText =
            pdf.splitTextToSize(
                agreement.terms || '',
                165
            );

        wrappedText.forEach(line => {

            if (y > 250) {

                pdf.addPage();

                y = 20;
            }

            pdf.text(
                line,
                20,
                y
            );

            y += 6;
        });

        y += 25;

        if (y > 240) {

            pdf.addPage();

            y = 40;
        }

        pdf.line(
            25,
            y,
            80,
            y
        );

        pdf.line(
            120,
            y,
            175,
            y
        );

        y += 7;

        pdf.text(
            'Tenant Signature',
            25,
            y
        );

        pdf.text(
            'Owner Signature',
            120,
            y
        );

        pdf.setFontSize(9);

        pdf.text(
            'Generated by Property Management System',
            pageWidth / 2,
            pageHeight - 10,
            {
                align: 'center'
            }
        );

        const pdfBlob = pdf.output('blob');

        const base64 =
            await this.blobToBase64(pdfBlob);

        await savePdf({
            leaseAgreementId: this.recordId,
            fileName: agreement.name,
            base64Pdf: base64
        });

        pdf.save(`${agreement.name}.pdf`);

        this.showToast(
            'Success',
            'Lease Agreement downloaded successfully.',
            'success'
        );

        setTimeout(() => {
            this.dispatchEvent(new CloseActionScreenEvent());
        }, 800);
    } catch (error) {

        this.showToast(
            'Error',
            error.body?.message || 'Unable to generate PDF.',
            'error'
        );

    } finally {

        this.isLoading = false;
    }
}

blobToBase64(blob) {

    return new Promise((resolve, reject) => {

        const reader = new FileReader();

        reader.onloadend = () => {
            resolve(
                reader.result.split(',')[1]
            );
        };

        reader.onerror = reject;

        reader.readAsDataURL(blob);
    });
}

showToast(title, message, variant) {

    this.dispatchEvent(
        new ShowToastEvent({
            title,
            message,
            variant
        })
    );
}

}