public with sharing class PropertyTriggerHandler {

    public void beforeInsert(List<Property__c> newProperties) {
    }

    public void beforeUpdate(
        List<Property__c> newProperties,
        Map<Id, Property__c> oldMap
    ) {
    }

    public void beforeDelete(List<Property__c> oldProperties) {
    }

    public void afterInsert(List<Property__c> newProperties) {
    }

    public void afterUpdate(
        List<Property__c> newProperties,
        Map<Id, Property__c> oldMap
    ) {
    }

    public void afterDelete(List<Property__c> oldProperties) {
    }

    public void afterUndelete(List<Property__c> newProperties) {
    }

}